"use strict";
(function(root){
  function normalize(text){return String(text??"").replace(/ي/g,"ی").replace(/ك/g,"ک").replace(/[\u200c\u200e\u200f]/g," ").replace(/[\u064b-\u065f]/g,"").replace(/\s+/g," ").toLowerCase().trim();}
  function sectionText(section){return [section.title,...section.blocks.map(b=>b.text??b.rows?.flat().join(" ")??"")].join(" ");}
  function filterSections(sections,query){const q=normalize(query);return q?sections.filter(section=>normalize(sectionText(section)).includes(q)):sections;}
  const api={normalize,sectionText,filterSections};if(typeof module!=="undefined"&&module.exports)module.exports=api;root.scoreboardManual=api;if(!root.document)return;
  let query="";const doc=root.document;
  api.render=container=>{
    const guide=root.scoreboardGuide;container.replaceChildren();const intro=doc.createElement("div");intro.className="card guide-intro";const title=doc.createElement("h2");title.textContent="راهنمای کامل نرم‌افزار";const text=doc.createElement("p");text.textContent=`نسخه ${guide.version} · راهنمای فارسی آفلاین از نصب تا پایان مسابقه. از فهرست، بخش موردنظر را انتخاب کنید یا در متن راهنما جست‌وجو کنید.`;const label=doc.createElement("label");label.htmlFor="guide-search";label.textContent="جست‌وجو در راهنما";const input=doc.createElement("input");input.type="search";input.id="guide-search";input.placeholder="مثلاً قرعه‌کشی، لاین، جریمه یا پشتیبان";input.value=query;const clear=doc.createElement("button");clear.id="guide-clear";clear.className="btn ghost";clear.textContent="پاک‌کردن جست‌وجو";const count=doc.createElement("p");count.id="guide-search-status";count.setAttribute("role","status");const field=doc.createElement("div");field.className="field";field.append(label,input);intro.append(title,text,field,clear,count);container.append(intro);
    const layout=doc.createElement("div");layout.className="manual-layout";const toc=doc.createElement("nav");toc.className="card manual-toc";toc.setAttribute("aria-label","فهرست راهنما");const content=doc.createElement("div");content.id="guide-sections";layout.append(toc,content);container.append(layout);
    const update=()=>{query=input.value;const sections=filterSections(guide.sections,query);toc.replaceChildren();content.replaceChildren();count.textContent=`${sections.length.toLocaleString("fa-IR")} بخش از ${guide.sections.length.toLocaleString("fa-IR")} بخش`;const heading=doc.createElement("h3");heading.textContent="فهرست بخش‌ها";toc.append(heading);for(const section of sections){const link=doc.createElement("a");link.href=`#${section.id}`;link.textContent=section.title;link.onclick=event=>{event.preventDefault();const target=doc.getElementById(section.id);target.scrollIntoView({block:"start"});target.focus({preventScroll:true});};toc.append(link);const article=doc.createElement("article");article.className="card manual-section";article.id=section.id;article.tabIndex=-1;const h=doc.createElement("h2");h.textContent=section.title;article.append(h);for(const block of section.blocks){if(block.type==="table"){const wrap=doc.createElement("div");wrap.className="table-wrap";const table=doc.createElement("table");for(let i=0;i<block.rows.length;i++){const row=doc.createElement("tr");for(const value of block.rows[i]){const cell=doc.createElement(i?"td":"th");cell.textContent=value;row.append(cell);}table.append(row);}wrap.append(table);article.append(wrap);}else{const element=doc.createElement(block.type==="code"?"pre":block.type==="heading"?"h3":"p");element.textContent=block.text;if(block.type==="code")element.dir="ltr";if(block.type==="item")element.className="manual-item";article.append(element);}}content.append(article);}if(!sections.length){const empty=doc.createElement("p");empty.className="card";empty.textContent="موضوعی پیدا نشد؛ عبارت کوتاه‌تری بنویسید یا جست‌وجو را پاک کنید.";content.append(empty);}clear.disabled=!query;};input.addEventListener("input",update);clear.onclick=()=>{input.value="";update();input.focus();};update();
  };
})(typeof window!=="undefined"?window:globalThis);
