"use strict";
(function(root){
  const topics={
    dashboard:["تابلوی نتایج","جدول زنده بلافاصله پس از ذخیره تغییر می‌کند؛ نتیجه موقت تا تأیید سرداور رسمی نیست. برای نمایش سالن، صفحه کل مسابقات، هر رشته یا انفرادی ترکیبی را انتخاب و منتشر کنید."],
    entry:["ثبت نتیجه داور","ابتدا تیم و رشته را با برگه داوری تطبیق دهید. زمان را با دقیقه، ثانیه و صدم ثبت کنید؛ جریمه با واحد ثانیه است. ذخیره، نتیجه را فوراً به تابلو زنده و صف سرداور می‌فرستد."],
    teams:["تیم‌ها و ورزشکاران","پیش از قرعه‌کشی و ثبت نتیجه، فهرست همه تیم‌ها و دو ورزشکار هر تیم را کامل کنید. حداقل دو تیم برای قرعه لازم است. تیمی که پس از شروع ترکیبی اضافه شود، وارد نوبت تثبیت‌شده این رشته نمی‌شود."],
    approvals:["تأیید سرداور","نتایج موقت را بررسی و تأیید و قفل کنید. نتیجه ترکیبی ناقص قابل تأیید نیست. برای اصلاح نتیجه رسمی ابتدا آن را باز کنید؛ سپس دوباره ذخیره و تأیید کنید."],
    draw:["قرعه‌کشی و نوبت اجرا","قرعه فقط ترتیب حضور تیم‌ها را تعیین می‌کند و امتیاز نمی‌دهد. می‌توانید نوبت قرعه فیزیکی را دستی وارد کنید یا ترتیب تصادفی بسازید. قرعه را پیش از اولین نتیجه انجام دهید؛ نوبت‌ها پس از شروع ثبت نتایج ثابت می‌شوند."],
    settings:["تنظیمات و نمایشگر","عنوان، تاریخ، محل، لوگوها، زیرنویس، صدا و گردش صفحات را تنظیم و ذخیره کنید. تغییرات در نمایشگر سالن و گزارش‌ها اعمال می‌شوند. اتصال و حالت Extend ویندوز را نیز جداگانه بررسی کنید."],
    audit:["سوابق تغییرات","این دفتر آخرین عملیات ثبت، تأیید، اصلاح، حذف و تنظیمات را همراه زمان نشان می‌دهد. حداکثر ۳۰۰ سابقه نگهداری می‌شود. پاک‌سازی کامل، این سوابق را هم حذف می‌کند."],
    guide:["راهنمای کامل نرم‌افزار","از منوی «راهنمای نرم‌افزار» متن کامل فارسی را بخوانید. فهرست بخش‌ها و جست‌وجوی متن به شما کمک می‌کند موضوع موردنیاز را پیدا کنید. این راهنما بدون اینترنت در دسترس است."],
    backup:["ذخیره نسخه پشتیبان","یک فایل JSON کامل در مسیر دلخواه خود ذخیره کنید. فایل شامل تیم‌ها، نتایج، قرعه‌ها، تنظیمات و لوگوهاست. بهتر است یک کپی روی حافظه جداگانه نگه دارید. بازیابی فعلاً با جایگزینی competition-data.json هنگام بسته‌بودن برنامه انجام می‌شود؛ مراحل دقیق در راهنمای کامل آمده است."],
    display:["بازکردن نمایشگر سالن","پنجره مستقل نتایج را باز می‌کند. در تنظیمات می‌توانید نمایشگر مقصد و Extend یا Mirror را انتخاب کنید. اگر تنها یک مانیتور باشد پنجره عادی باز می‌شود. صفحه سالن اجازه تغییر یا حذف داده‌های داوری را ندارد."],
    pdf:["گزارش PDF نتایج","فایل PDF رسمی فقط نتایج تأییدشده را محاسبه می‌کند؛ نتیجه موقت در رتبه‌بندی رسمی آن وارد نمی‌شود. عنوان، تاریخ، لوگوها و نام حامی سازمانی از تنظیمات مسابقه گرفته می‌شوند."],
    publish:["انتخاب و انتشار صفحه سالن","صفحه دلخواه را انتخاب کنید و «نمایش این صفحه در سالن» را بزنید تا همان جدول روی نمایشگر عمومی قرار گیرد. انتخاب فهرست به‌تنهایی صفحه سالن را تغییر نمی‌دهد."],
    ranks:["رتبه زنده و مجموع رتبه‌ها","زمان نهایی کمتر در رشته‌های زمانی بهتر است؛ نمره علمی بیشتر بهتر است. رتبه کل پس از تکمیل هر پنج رشته و از مجموع رتبه‌های رشته‌ها تعیین می‌شود؛ مجموع کمتر بهتر است. تساوی‌ها رتبه مشترک دارند، مانند ۱، ۱، ۳. نوبت اجرا با رتبه متفاوت است."],
    status:["وضعیت و تکمیل نتایج","ثبت نشده: رکوردی وجود ندارد. موقت: ذخیره شده و منتظر تأیید سرداور است. تأییدشده: رسمی و قفل است. در ترکیبی، هیچ رکورد Pending، یک رکورد Partial و دو رکورد Completed است؛ تیم ناقص هنوز رتبه تیمی ندارد."],
    teamName:["نام تیم","نام تیم الزامی و نباید تکراری باشد. کدهایی مانند T01 خودکار ساخته می‌شوند. نام و مجموعه را با فهرست رسمی مسابقه تطبیق دهید."],
    organization:["شرکت یا مجموعه تیم","نام شرکت یا سازمان تیم را وارد کنید تا در فهرست‌ها، قرعه و گزارش‌ها مشخص باشد. این فیلد بر زمان و امتیاز اثر نمی‌گذارد."],
    athlete:["نام ورزشکار","نام ورزشکار را با برگه داوری تطبیق دهید. در ترکیبی، هر تیم دو جایگاه مستقل برای دور اول و دوم دارد. پاک‌کردن نام ثبت‌شده باید از دکمه حذف و تأیید دومرحله‌ای انجام شود."],
    discipline:["انتخاب رشته مسابقه","آزمون علمی با نمره ارزیابی می‌شود؛ آبرسانی، امدادی مهارت‌محور و ارتفاع با زمان نهایی؛ عملیات ترکیبی با دو رکورد مستقل و میانگین زمان نهایی دو ورزشکار. پیش از ذخیره، رشته انتخابی را کنترل کنید."],
    teamSelect:["انتخاب تیم برای ثبت نتیجه","تیم حاضر روی لاین را انتخاب کنید. با تغییر تیم، رکورد قبلی همان تیم در فرم قرار می‌گیرد؛ پیش از ذخیره نام تیم و ورزشکار را دوباره بررسی کنید."],
    time:["زمان: دقیقه، ثانیه و صدم","هر سه جزء زمان را انتخاب کنید؛ حتی جزء صفر باید صریحاً انتخاب شود. نمونه ۰۱:۱۲.۳۴ یعنی یک دقیقه، ۱۲ ثانیه و ۳۴ صدم. زمان رشته عملیاتی باید بزرگ‌تر از صفر باشد؛ عدد جریمه را جداگانه وارد کنید."],
    scientific:["آزمون علمی","نمره را از صفر تا ۱۰۰ وارد کنید. نمره بیشتر رتبه بهتر دارد. زمان پاسخ‌گویی برای رفع تساوی است؛ در نمره مساوی، زمان ثبت‌شده کمتر بهتر است. زمان پاسخ‌گویی اختیاری است، اما اگر انتخاب شود نمی‌تواند صفر باشد."],
    penalty:["جریمه و واحد آن","عدد جریمه را به ثانیه وارد کنید؛ برنامه آن را به زمان اضافه می‌کند. در ترکیبی جریمه فقط متعلق به ورزشکار دور انتخاب‌شده است و داخل میانگین دو زمان نهایی قرار می‌گیرد. برای پاک‌کردن جریمه مثبت، از دکمه حذف جریمه با تأیید دومرحله‌ای استفاده کنید."],
    judge:["نام داور","نام ثبت‌کننده رکورد را برای پیگیری ثبت کنید. این نام همراه نتیجه ذخیره می‌شود و روی امتیاز اثر ندارد."],
    note:["شرح خطا یا توضیحات","علت جریمه، وضعیت خاص یا نکته لازم برای سرداور را بنویسید. توضیح به‌تنهایی جریمه ایجاد نمی‌کند؛ زمان جریمه باید در فیلد مربوط وارد شود."],
    combined:["دو دور مستقل عملیات ترکیبی","هر ورزشکار مستقل ذخیره می‌شود؛ برای ثبت نفر اول، زمان نفر دوم لازم نیست. رتبه انفرادی فوراً محاسبه می‌شود. پس از ثبت هر دو، امتیاز تیم برابر میانگین زمان نهایی دو ورزشکار است. جریمه مشترک منتقل‌شده از نسخه قدیمی جداگانه به امتیاز تیم افزوده می‌شود."],
    round:["انتخاب دور عملیات ترکیبی","دور ۱ ورزشکار اول هر تیم و دور ۲ ورزشکار دوم همان تیم است. برای ۲۲ تیم، شماره‌ها در دور اول ۱ تا ۲۲ و دور دوم ۲۳ تا ۴۴ هستند. شماره‌گذاری برای تعداد تیم‌های دیگر خودکار تطبیق می‌یابد."],
    lane:["شماره، گروه و لاین","لاین دور دوم همیشه مخالف دور اول همان تیم است. در هر گروه، دو تیم در لاین‌های ۱ و ۲ قرار می‌گیرند. نوبت‌ها با اولین رکورد ترکیبی تثبیت می‌شوند؛ تغییر یا حذف رکورد، نوبت تاریخی را آزاد نمی‌کند."],
    save:["ذخیره و ارسال نتیجه","ذخیره، نتیجه را فوراً با وضعیت موقت روی تابلو منتشر می‌کند. در عملیات ترکیبی فقط رکورد همان ورزشکار ذخیره می‌شود و نفر دوم می‌تواند بعداً ثبت شود. اگر نتیجه رسمی و قفل است، ابتدا از صف سرداور آن را برای اصلاح باز کنید."],
    approve:["تأیید و قفل نتیجه","سرداور پس از بررسی، نتیجه را رسمی و قفل می‌کند. نتیجه کامل ترکیبی باید هر دو رکورد را داشته باشد؛ نتیجه Partial قابل تأیید نیست. برای ویرایش رکورد قفل‌شده، ابتدا «بازکردن برای اصلاح» را بزنید."],
    reopen:["بازکردن نتیجه برای اصلاح","قفل نتیجه برداشته می‌شود و وضعیت آن موقت می‌گردد. رکورد را در فرم داور اصلاح کنید و برای رسمی‌شدن دوباره تأیید کنید. نتیجه بازشده در محاسبات رسمی PDF وارد نمی‌شود."],
    deletion:["حذف داده با دو تأیید","در مرحله اول ادامه را انتخاب کنید؛ سپس خلاصه داده را بررسی، دو ثانیه صبر و «تایید» را دقیق تایپ کنید. انصراف داده را حفظ می‌کند. تأیید پس از دو دقیقه یا تغییر داده نامعتبر می‌شود؛ دوباره آغاز کنید."],
    deleteTeam:["حذف تیم و نتایج","دو ورزشکار و تمام نتایج و رکوردهای انفرادی تیم حذف می‌شوند. نوبت‌های تاریخی و سوابق برای پیگیری باقی می‌مانند. این عملیات با حذف کامل نرم‌افزار متفاوت است و دو تأیید لازم دارد."],
    deleteAthlete:["پاک‌کردن ورزشکار","نام ورزشکار و رکورد همان دور حذف می‌شوند؛ جایگاه ورزشکار در تیم باقی می‌ماند. اگر تیم ترکیبی کامل بوده، ناقص می‌شود و رتبه تیمی آن کنار می‌رود. دو تأیید لازم است."],
    deleteRound:["حذف رکورد یک دور","فقط رکورد همین ورزشکار و جریمه آن حذف می‌شوند. نام و جایگاه ورزشکار باقی می‌مانند. تیم ممکن است Partial یا Pending شود و رتبه‌ها دوباره محاسبه شوند."],
    deletePenalty:["پاک‌کردن جریمه","فقط جریمه انتخاب‌شده پس از دو تأیید حذف می‌شود؛ نام و زمان خام باقی می‌مانند. نتیجه برای بررسی دوباره موقت می‌شود و رتبه‌های زنده به‌روز می‌شوند."],
    reset:["پاک‌کردن همه داده‌ها و شروع از صفر","پس از دو تأیید، دو ثانیه انتظار و تایپ «تایید»، همه تیم‌ها، ورزشکاران، نتایج، جریمه‌ها، قرعه‌ها، سوابق و پشتیبان‌های خودکار داخلی پاک می‌شوند. تنظیمات و لوگوها به حالت اولیه برمی‌گردند. فایل‌های PDF و پشتیبان‌های دستی بیرون از برنامه باقی می‌مانند. در صورت نیاز، پیش از آغاز پشتیبان دستی بگیرید."],
    drawScope:["محدوده قرعه‌کشی","ترتیب عمومی برای همه تیم‌هاست. قرعه اختصاصی یک رشته بر نوبت عمومی همان رشته اولویت دارد. وجود نتیجه در هر رشته، قرعه عمومی را قفل می‌کند؛ برای قرعه اختصاصی، فقط شروع همان رشته مانع است."],
    drawManual:["ثبت نوبت‌های دستی","نتیجه قرعه‌کشی فیزیکی را برای همه تیم‌ها وارد و ذخیره کنید. شماره‌ها باید از ۱ تا تعداد تیم‌ها، کامل و بدون تکرار باشند؛ برای ۲۲ تیم، ۱ تا ۲۲. حداقل دو تیم و نبود نتیجه در محدوده انتخابی لازم است."],
    drawAuto:["شروع قرعه‌کشی تصادفی","برنامه به هر تیم یک نوبت یکتا و تصادفی می‌دهد و آن را ذخیره می‌کند. این کار امتیاز یا رتبه را تغییر نمی‌دهد. حداقل دو تیم و نبود نتیجه در محدوده انتخابی لازم است."],
    redraw:["جایگزینی قرعه قبلی","اگر قرعه قبلی وجود دارد، پیش از اجرای مجدد یا جایگزینی دستی این گزینه را تیک بزنید. قرعه قبلی در سوابق باقی می‌ماند. تیک تأیید، قفل ناشی از شروع نتایج را باز نمی‌کند."],
    drawPDF:["PDF قرعه‌کشی","نوبت‌های همین قرعه با نام تیم‌ها و مجموعه‌ها در فایل PDF ذخیره می‌شوند. از بخش سوابق می‌توانید PDF قرعه‌های قدیمی را نیز دریافت کنید."],
    drawDisplay:["نمایش قرعه در سالن","نوبت‌های همین قرعه روی نمایشگر سالن قرار می‌گیرند. اعداد نمایش‌داده‌شده نوبت حضور هستند و رتبه امتیازی نیستند. از بازگشت سالن به نتایج برای برگشت به جدول کل استفاده کنید."],
    branding:["عنوان و مشخصات مسابقه","عنوان، محل و تاریخ برگزاری را برای نمایش در پنل، سالن و گزارش‌ها وارد و ذخیره کنید. تاریخ می‌تواند شمسی یا میلادی باشد. این مشخصات در محاسبه نتیجه اثر ندارند."],
    logo:["لوگوی مسابقه و حامی‌ها","تصویر واقعی PNG، JPEG یا WebP تا ۲ مگابایت انتخاب کنید. حداکثر سه لوگوی حامی مجاز است. تصاویر پس از ذخیره داخل داده محلی نگهداری می‌شوند و اینترنت لازم ندارند. گزینه بازگشت یا پاک‌کردن لوگو، تصویر سفارشی را حذف می‌کند."],
    ticker:["پیام پایین نمایشگر","پیام ثابت سالن را وارد و تنظیمات را ذخیره کنید. این پیام زیر نتایج نمایش داده می‌شود؛ اعلان تغییر نتیجه جداگانه و خودکار است."],
    audio:["صدای اعلان و آزمایش صدا","پخش اعلان نتیجه را روشن یا خاموش کنید و بلندی را از صفر تا ۱۰۰ تنظیم کنید. آزمایش صدا خروجی صوتی همین رایانه را بررسی می‌کند. تنظیمات را ذخیره و خروجی و بلندی صدای ویندوز را هم بررسی کنید."],
    rotation:["گردش و صفحه‌بندی سالن","گردش خودکار صفحات را در تنظیمات کنترل کنید. در سالن، توقف گردش فقط همان پنجره را موقتاً متوقف می‌کند. کاهش حرکت سیستم نیز گردش خودکار را متوقف می‌کند. اگر تنها یک صفحه وجود دارد، قبل و بعد غیرفعال‌اند."],
    windowMode:["Extend و Mirror","Extend پنجره را روی نمایشگر دوم و در صورت وجود تمام‌صفحه باز می‌کند. Mirror پیش‌نمایش همان تابلوی عمومی روی اصلی است. حالت سیستم‌عامل را با Win+P انتخاب کنید؛ برنامه Duplicate یا Extend ویندوز را تغییر نمی‌دهد."],
    targetDisplay:["نمایشگر مقصد","نمایشگر متصل را انتخاب کنید یا انتخاب خودکار را نگه دارید، سپس پنجره سالن را باز کنید. در Extend، انتخاب خودکار نمایشگر دوم را ترجیح می‌دهد. برای خروجی مستقل، ویندوز هم باید روی Extend باشد."],
    closeDisplay:["بستن نمایشگر سالن","فقط پنجره عمومی سالن بسته می‌شود؛ تیم‌ها، نتایج و تنظیمات حفظ می‌شوند. با بازکردن مجدد، آخرین داده ذخیره‌شده نمایش داده می‌شود."],
    settingsSave:["ذخیره تنظیمات","تغییر عنوان، تاریخ، محل، تصاویر، زیرنویس، صدا و گردش را اعمال و ذخیره می‌کند. انتخاب فایل تصویر یا تغییر فرم به‌تنهایی کافی نیست. اگر داده هنگام خواندن فایل تغییر کند، دوباره فرم را بررسی و ذخیره کنید."]
  };
  const controlTopics={"guide-search":"guide","guide-clear":"guide","backup-btn":"backup","backup-alt":"backup","display-btn":"display","open-display-alt":"display","export-standings":"pdf","publish-leaderboard":"publish","leaderboard-scope":"publish","add-team":"teams","team-name":"teamName","team-org":"organization","team-athlete-1":"athlete","team-athlete-2":"athlete","discipline":"discipline","team":"teamSelect","athlete-primary":"athlete","athlete-secondary":"athlete","scientific-score":"scientific","penalty":"penalty","judge":"judge","note":"note","save-result":"save","combined-round":"round","delete-round":"deleteRound","delete-round-penalty":"deletePenalty","delete-legacy-penalty":"deletePenalty","clear-result-penalty":"deletePenalty","draw-scope":"drawScope","save-manual-draw":"drawManual","run-draw":"drawAuto","confirm-redraw":"redraw","show-draw":"drawDisplay","show-standings":"dashboard","export-draw":"drawPDF","competition-name":"branding","competition-venue":"branding","event-date":"branding","competition-logo-file":"logo","reset-competition-logo":"logo","display-message":"ticker","audio-enabled":"audio","audio-volume":"audio","test-sound":"audio","auto-rotate":"rotation","save-settings":"settingsSave","window-mode":"windowMode","target-display":"targetDisplay","close-display":"closeDisplay","reset-all":"reset","delete-next":"deletion","delete-final":"deletion","delete-confirmation":"deletion","delete-cancel":"deletion","previous-page":"rotation","next-page":"rotation","pause-pages":"rotation"};
  const headingTopics={"جدول امتیازات تیمی":"ranks","تابلو زندهٔ هر رشته":"publish","فرم ثبت نتیجه داور":"entry","کنترل قبل از ثبت":"entry","صف تأیید سرداور":"approvals","آخرین نتایج قفل‌شده":"reopen","افزودن تیم":"teams","مشخصات مسابقه":"settings","نمایشگر دوم":"display","دفتر ثبت تغییرات":"audit","قرعه‌کشی ترتیب حضور تیم‌ها":"draw","ورود دستی نوبت قرعه‌کشی فیزیکی":"drawManual"};
  const columnTopics={"رتبه زنده":"ranks","رتبه امتیازی":"ranks","رتبه":"ranks","نوبت عمومی":"drawScope","نوبت اجرا":"draw","تیم":"teamSelect","رشته":"discipline","نتیجه":"save","داور":"judge","مجموع":"ranks","مجموع رتبه":"ranks","تکمیل":"status","وضعیت":"status","ورزشکار":"athlete","ورزشکار / تیم":"athlete","زمان خام":"time","رکورد خام":"time","زمان پاسخ":"scientific","زمان پاسخ‌گویی":"scientific","زمان نهایی":"combined","نمره نهایی":"scientific","جریمه":"penalty","شماره":"round","دور / گروه / لاین":"lane","شماره / دور / لاین":"lane"};
  function drawAvailability(state,scope="all",busy=false){
    if(state.teams.length<2)return {allowed:false,reason:"حداقل دو تیم ثبت کنید؛ اکنون تعداد تیم‌ها کمتر از دو است."};
    if(busy)return {allowed:false,reason:"قرعه‌کشی در حال ذخیره است؛ تا پایان عملیات صبر کنید."};
    if(((scope==="all"||scope==="combined")&&state.combinedStartOrder?.length)||state.results.some(r=>scope==="all"||r.disciplineId===scope))return {allowed:false,reason:scope==="all"?"ثبت نتایج شروع شده است؛ ترتیب عمومی تیم‌ها برای حفظ نوبت و لاین‌ها قفل است.":"ثبت نتایج این رشته شروع شده است؛ نوبت‌های آن ثابت و غیرقابل تغییر هستند."};
    return {allowed:true,reason:"دکمه آماده است؛ پیش از اجرا فهرست تیم‌ها را کامل کنید."};
  }
  function getTopic(key,context={}){
    const data=topics[key];if(!data)return null;const paragraphs=[data[1]];
    if(["drawAuto","drawManual","drawScope","redraw"].includes(key)&&context.state){paragraphs.push(drawAvailability(context.state,context.drawScope,context.drawBusy).reason);if(context.state.draws.some(d=>d.disciplineId===context.drawScope))paragraphs.push("برای جایگزینی قرعه موجود، گزینه تأیید قرعه‌کشی مجدد را تیک بزنید.");}
    if(key==="save"&&context.state){const r=context.state.results.find(r=>r.teamId===Number(context.teamId)&&r.disciplineId===context.disciplineId);if(r?.status==="approved")paragraphs.push("اکنون این نتیجه قفل است؛ برای فعال‌شدن ذخیره، از بخش تأیید سرداور آن را برای اصلاح باز کنید.");if(context.disciplineId==="combined"){paragraphs.push("اکنون فقط دور انتخاب‌شده را ثبت می‌کنید؛ پرکردن زمان ورزشکار دور دیگر لازم نیست.");if(context.slot&&!context.slot.lane)paragraphs.push("این تیم در فهرست ثابت عملیات ترکیبی نیست؛ پس از شروع ترکیبی، افزودن تیم جدید نوبت آن را ایجاد نمی‌کند.");}}
    if(key==="approve"&&context.result?.completionStatus==="Partial")paragraphs.push("این نتیجه فقط یک ورزشکار ثبت‌شده دارد؛ پس از ذخیره ورزشکار دیگر، تأیید تیمی فعال می‌شود.");
    if(key==="lane"&&context.slot)paragraphs.push(`ورزشکار انتخاب‌شده: شماره ${context.slot.athleteNumber}، دور ${context.slot.round}، گروه ${context.slot.heat} و لاین ${context.slot.lane}.`);
    if(key==="rotation"&&context.pageCount!=null){if(context.pageCount===1)paragraphs.push("اکنون فقط یک صفحه وجود دارد؛ دکمه‌های صفحه‌بندی غیرفعال‌اند.");if(context.state?.settings.autoRotate===false)paragraphs.push("گردش خودکار در تنظیمات خاموش است؛ برای ادامه گردش، آن را در پنل مدیریت روشن و ذخیره کنید.");if(context.reducedMotion)paragraphs.push("کاهش حرکت سیستم فعال است؛ گردش خودکار متوقف است.");}
    return {key,title:data[0],paragraphs};
  }
  function topicForControl(node){if(controlTopics[node.id])return controlTopics[node.id];if(node.dataset.view)return node.dataset.view;if(node.dataset.action)return node.dataset.action;if(node.dataset.orderTeam)return "drawManual";if(node.dataset.exportDraw)return "drawPDF";if(node.dataset.deleteKind)return {team:"deleteTeam",athlete:"deleteAthlete",round:"deleteRound",round_penalty:"deletePenalty",result_penalty:"deletePenalty",result:"deletion"}[node.dataset.deleteKind];if(/^(primary|secondary|scientific)-[msh]$/.test(node.id))return node.id.startsWith("scientific")?"scientific":"time";if(/^(reset-)?sponsor-\d$/.test(node.id))return "logo";return null;}
  const api={topics,controlTopics,drawAvailability,getTopic,topicForControl};
  if(typeof module!=="undefined"&&module.exports)module.exports=api;
  root.scoreboardHelp=api;
  if(!root.document)return;
  let getContext=()=>({}),openGuide;const doc=root.document;
  function showTopic(key,source){const topic=getTopic(key,getContext(source));if(!topic)return;doc.getElementById("context-help-dialog")?.close();doc.getElementById("context-help-dialog")?.remove();const dialog=doc.createElement("dialog");dialog.id="context-help-dialog";dialog.className="context-help-dialog";dialog.setAttribute("aria-labelledby","context-help-title");const heading=doc.createElement("h2");heading.id="context-help-title";heading.textContent=topic.title;dialog.append(heading);for(const text of topic.paragraphs){const p=doc.createElement("p");p.textContent=text;dialog.append(p);}const actions=doc.createElement("div");actions.className="context-help-actions";const close=doc.createElement("button");close.className="help-close";close.id="context-help-close";close.textContent="بستن راهنما";const finish=()=>{dialog.close();dialog.remove();if(source?.isConnected)source.focus();};close.onclick=finish;actions.append(close);if(openGuide&&!doc.querySelector(".delete-dialog[open]")){const full=doc.createElement("button");full.className="help-full";full.id="context-help-full";full.textContent="مطالعه راهنمای کامل";full.onclick=()=>{finish();openGuide();};actions.append(full);}dialog.append(actions);dialog.addEventListener("cancel",event=>{event.preventDefault();finish();});doc.body.append(dialog);dialog.showModal();close.focus();}
  function attach(node,key,forValue){if(!key||!topics[key]||node.dataset.helpAttached)return;node.dataset.helpAttached="true";const wrap=doc.createElement("span");wrap.className=node.tagName==="BUTTON"?"help-control-group":"help-label-group";node.before(wrap);wrap.append(node);const icon=doc.createElement("button");icon.type="button";icon.className="help-icon";icon.dataset.helpTopic=key;icon.dataset.helpFor=forValue||node.id||key;icon.textContent="؟";icon.title=`راهنمای ${topics[key][0]}`;icon.setAttribute("aria-label",icon.title);icon.onclick=()=>showTopic(key,icon);icon._helpSource=node;wrap.append(icon);}
  api.showTopic=showTopic;
  api.install=options=>{getContext=source=>options?.getContext?.(source?._helpSource||source)||{};openGuide=options?.openGuide;};
  api.decorate=(rootNode=doc)=>{
    for(const node of rootNode.querySelectorAll("button:not(.help-icon),input,select,textarea")){const key=topicForControl(node);if(!key||node.dataset.helpAttached)continue;if(node.tagName==="BUTTON")attach(node,key,node.id||node.dataset.action||node.dataset.deleteKind||key);else{const label=node.closest("label")||Array.from(rootNode.querySelectorAll("label")).find(l=>l.htmlFor===node.id)||node.closest(".field,.time-part")?.querySelector("label")||node.closest(".switch-row")?.querySelector("label,span");if(label){attach(label,key,node.id);node.dataset.helpAttached="true";}}}
    for(const metric of rootNode.querySelectorAll(".metric span:not(.help-label-group)"))attach(metric,"status");
    for(const heading of rootNode.querySelectorAll("h2,h3")){const key=headingTopics[heading.textContent.trim()]||(heading.closest("section")?.querySelector("#show-draw")?"draw":null);if(key)attach(heading,key);}
    for(const th of rootNode.querySelectorAll("th")){const text=th.textContent.trim(),key=columnTopics[text]||(text==="آزمون علمی"?"scientific":text==="عملیات ترکیبی"?"combined":["آبرسانی","امدادی مهارت‌محور","نجات از ارتفاع"].includes(text)?"time":null);if(key&&!th.dataset.helpAttached){th.dataset.helpAttached="true";const icon=doc.createElement("button");icon.type="button";icon.className="help-icon";icon.dataset.helpTopic=key;icon.textContent="؟";icon.setAttribute("aria-label",`راهنمای ${text}`);icon.title=icon.getAttribute("aria-label");icon.onclick=()=>showTopic(key,icon);const label=doc.createElement("span");label.className="help-column-label";label.textContent=text;th.replaceChildren(label," ",icon);}}
  };
  api.attach=attach;
})(typeof window!=="undefined"?window:globalThis);
