"use strict";
const {test}=require("node:test");
const assert=require("node:assert/strict");
const fs=require("node:fs"),path=require("node:path"),os=require("node:os");
const {CompetitionStore}=require("../store.cjs");
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"imidro-reset-"));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const store=new CompetitionStore(dir);const initial=store.view();store.addTeam({name:"آزمایشی",athletePrimary:"آزمایش ۱",athleteSecondary:"آزمایش ۲"});store.addTeam({name:"دوم"});store.createDraw();store.saveRoundScore({teamId:1,round:1,rawMs:70000,penaltyMs:5000});store.saveRoundScore({teamId:1,round:2,rawMs:80000});store.approveResult({resultId:store.view().results[0].id});store.saveResult({teamId:2,disciplineId:"water",rawPrimaryMs:65000});store.updateSettings({competitionLogo:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZ2kAAAAASUVORK5CYII=",competitionName:"تمرین",eventDate:"آزمایش",venue:"تست",audioEnabled:false,audioVolume:0,autoRotate:false,displayMessage:"داده تست"});store.setDisplay({mode:"individual"});return {store,dir,initial};}
function confirm(store,review){if(store.deletionChallenges.has(review.token))store.deletionChallenges.get(review.token).readyAt=Date.now()-1;return store.confirmDeletion({token:review.token,confirmation:"تایید"});}
test("full reset restores first-launch defaults, clears backups and survives reopening",t=>{const {store,dir,initial}=fixture(t);const exported=path.join(dir,"manual-export.json");store.exportSnapshot(exported);const previous=store.view();const review=store.prepareDeletion({kind:"reset"});assert.match(review.summary,/پشتیبان/);assert.deepEqual(store.view(),previous);const reset=confirm(store,review);for(const key of ["teams","athletes","roundScores","results","draws","audits","combinedStartOrder","combinedSlots","individualLeaderboard","standings"])assert.deepEqual(reset[key],[]);assert.deepEqual(reset.settings,initial.settings);assert.deepEqual(reset.disciplines,initial.disciplines);for(const key of ["nextTeamId","nextAthleteId","nextRoundScoreId","nextResultId","nextAuditId"])assert.equal(reset[key],1);assert.ok(reset.revision>previous.revision);assert.deepEqual(fs.readdirSync(store.backupPath),[]);assert.ok(!fs.existsSync(store.resetBackupPath));assert.ok(fs.existsSync(exported));assert.deepEqual(new CompetitionStore(dir).view(),reset);assert.throws(()=>store.confirmDeletion({token:review.token,confirmation:"تایید"}),/منقضی/);store.addTeam({name:"تیم واقعی"});assert.equal(store.view().teams[0].code,"T01");assert.ok(fs.readdirSync(store.backupPath).length);});
test("reset enforces delay, typed confirmation, expiry and stale-review rejection",t=>{const {store}=fixture(t);const before=store.view();let r=store.prepareDeletion({kind:"reset"});assert.throws(()=>store.confirmDeletion({token:r.token,confirmation:"تایید"}),/دو ثانیه/);store.deletionChallenges.get(r.token).readyAt=0;assert.throws(()=>store.confirmDeletion({token:r.token,confirmation:"yes"}),/کلمه/);assert.deepEqual(store.view(),before);store.deletionChallenges.get(r.token).expiresAt=0;assert.throws(()=>confirm(store,r),/منقضی/);r=store.prepareDeletion({kind:"reset"});store.addTeam({name:"پس از بررسی"});assert.throws(()=>confirm(store,r),/تغییر/);assert.equal(store.view().teams.length,3);r=store.prepareDeletion({kind:"reset"});store.prepareDeletion({kind:"team",id:1});assert.throws(()=>confirm(store,r),/منقضی/);});
test("failed atomic reset keeps current data and automatic backups",t=>{const {store,dir}=fixture(t);const before=store.view(),files=fs.readdirSync(store.backupPath);const original=fs.renameSync;const r=store.prepareDeletion({kind:"reset"});fs.renameSync=(source,target)=>{if(target===store.dataPath)throw new Error("disk blocked");return original(source,target);};try{assert.throws(()=>confirm(store,r),/disk blocked/);}finally{fs.renameSync=original;}assert.deepEqual(store.view(),before);assert.deepEqual(new CompetitionStore(dir).view(),before);assert.deepEqual(fs.readdirSync(store.backupPath),files);assert.ok(!fs.existsSync(store.resetBackupPath));});
test("startup completes backup cleanup after interrupted reset",t=>{const {store,dir}=fixture(t);confirm(store,store.prepareDeletion({kind:"reset"}));fs.mkdirSync(store.resetBackupPath);fs.writeFileSync(path.join(store.resetBackupPath,"old.json"),"old test data");const reopened=new CompetitionStore(dir);assert.equal(reopened.view().teams.length,0);assert.ok(!fs.existsSync(store.resetBackupPath));});

test("an upload started before reset cannot restore old settings afterwards",t=>{const {store}=fixture(t);const pending={expectedRevision:store.view().revision,competitionName:"old test upload"};confirm(store,store.prepareDeletion({kind:"reset"}));const empty=store.view();assert.throws(()=>store.updateSettings(pending),/تغییر/);assert.deepEqual(store.view(),empty);});
